In [1]:
import pandas as pd
import numpy as np
import collections
import sklearn.preprocessing as preprocessing

In [2]:
df_categ = pd.read_json('dados.json',encoding="utf-8")
df_categ['user_id'] = range(0,len(df_categ))
# df_categ.set_index(df_categ['user_id'], inplace=True)
df_categ.tail()

,habilidades,horas_disponiveis,segmento,tipo_user,user_id
133,"[marketing-digital, css, machine-learning]",5,fashiontech,user,133
134,"[branding, php, cakephp, seo, ionic]",6,healthtech,user,134
135,"[js, big-data, angular]",4,fintech,user,135
136,"[machine-learning, php, cakephp]",8,adtech,startup,136
137,"[seo, angular, marketing-digital, ionic]",4,healthtech,user,137

In [3]:
# Transformando coluna de segmentos
segmentos_dummy = pd.get_dummies(df_categ['segmento'])
df_categ.drop('segmento',axis=1,inplace=True)
df_categ = df_categ.join(segmentos_dummy)

In [4]:
df_categ.tail()

,habilidades,horas_disponiveis,tipo_user,user_id,adtech,agritech,biotech,edtech,fashiontech,fintech,healthtech
133,"[marketing-digital, css, machine-learning]",5,user,133,0,0,0,0,1,0,0
134,"[branding, php, cakephp, seo, ionic]",6,user,134,0,0,0,0,0,0,1
135,"[js, big-data, angular]",4,user,135,0,0,0,0,0,1,0
136,"[machine-learning, php, cakephp]",8,startup,136,1,0,0,0,0,0,0
137,"[seo, angular, marketing-digital, ionic]",4,user,137,0,0,0,0,0,0,1

In [5]:
# Transformando coluna tipo_user
label_encoder = preprocessing.LabelEncoder()
label_encoder.fit(df_categ['tipo_user'])
label_encoder.classes_
df_categ['tipo_user'] = label_encoder.transform(df_categ['tipo_user'])

In [6]:
df_categ.tail()

,habilidades,horas_disponiveis,tipo_user,user_id,adtech,agritech,biotech,edtech,fashiontech,fintech,healthtech
133,"[marketing-digital, css, machine-learning]",5,1,133,0,0,0,0,1,0,0
134,"[branding, php, cakephp, seo, ionic]",6,1,134,0,0,0,0,0,0,1
135,"[js, big-data, angular]",4,1,135,0,0,0,0,0,1,0
136,"[machine-learning, php, cakephp]",8,0,136,1,0,0,0,0,0,0
137,"[seo, angular, marketing-digital, ionic]",4,1,137,0,0,0,0,0,0,1

In [286]:
# Scaling coluna de horas_disponiveis
# Mean = 0 and std = 1
# scaler = preprocessing.StandardScaler()
# scaled_horas = scaler.fit_transform(df_categ['horas_disponiveis'].values.reshape(-1,1))
# df_categ['horas_disponiveis'] = scaled_horas
# df_categ['horas_disponiveis'].describe()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)

count    1.380000e+02
mean    -1.094133e-16
std      1.003643e+00
min     -1.230689e+00
25%     -5.567405e-01
50%      1.172085e-01
75%      1.465106e+00
max      1.465106e+00
Name: horas_disponiveis, dtype: float64

In [187]:
df_categ.tail()

,habilidades,horas_disponiveis,tipo_user,user_id,adtech,agritech,biotech,edtech,fashiontech,fintech,healthtech
133,"[marketing-digital, css, machine-learning]",-0.556740,1,133,0,0,0,0,1,0,0
134,"[branding, php, cakephp, seo, ionic]",0.117209,1,134,0,0,0,0,0,0,1
135,"[js, big-data, angular]",-1.230689,1,135,0,0,0,0,0,1,0
136,"[machine-learning, php, cakephp]",1.465106,0,136,1,0,0,0,0,0,0
137,"[seo, angular, marketing-digital, ionic]",-1.230689,1,137,0,0,0,0,0,0,1

In [7]:
# Retirando linhas com habilidades em branco

for line in df_categ.itertuples():
    if line.habilidades == ['']:
        print (line)
        df_categ = df_categ[df_categ.user_id != line.user_id]
        print(50*"*")

Pandas(Index=40, habilidades=[''], horas_disponiveis=6, tipo_user=1, user_id=40, adtech=0, agritech=0, biotech=0, edtech=0, fashiontech=0, fintech=0, healthtech=1)
**************************************************
Pandas(Index=42, habilidades=[''], horas_disponiveis=5, tipo_user=1, user_id=42, adtech=0, agritech=1, biotech=0, edtech=0, fashiontech=0, fintech=0, healthtech=0)
**************************************************
Pandas(Index=43, habilidades=[''], horas_disponiveis=6, tipo_user=1, user_id=43, adtech=0, agritech=0, biotech=1, edtech=0, fashiontech=0, fintech=0, healthtech=0)
**************************************************
Pandas(Index=50, habilidades=[''], horas_disponiveis=8, tipo_user=0, user_id=50, adtech=0, agritech=0, biotech=0, edtech=0, fashiontech=0, fintech=0, healthtech=1)
**************************************************
Pandas(Index=63, habilidades=[''], horas_disponiveis=8, tipo_user=1, user_id=63, adtech=0, agritech=0, biotech=0, edtech=0, fashiontech=0, fintech=1, healthtech=0)
**************************************************
Pandas(Index=65, habilidades=[''], horas_disponiveis=6, tipo_user=0, user_id=65, adtech=0, agritech=0, biotech=0, edtech=0, fashiontech=0, fintech=0, healthtech=1)
**************************************************
Pandas(Index=66, habilidades=[''], horas_disponiveis=8, tipo_user=1, user_id=66, adtech=1, agritech=0, biotech=0, edtech=0, fashiontech=0, fintech=0, healthtech=0)
**************************************************
Pandas(Index=69, habilidades=[''], horas_disponiveis=6, tipo_user=0, user_id=69, adtech=0, agritech=0, biotech=0, edtech=0, fashiontech=0, fintech=0, healthtech=1)
**************************************************
Pandas(Index=72, habilidades=[''], horas_disponiveis=6, tipo_user=0, user_id=72, adtech=0, agritech=0, biotech=0, edtech=1, fashiontech=0, fintech=0, healthtech=0)
**************************************************
Pandas(Index=74, habilidades=[''], horas_disponiveis=5, tipo_user=0, user_id=74, adtech=0, agritech=0, biotech=0, edtech=0, fashiontech=0, fintech=1, healthtech=0)
**************************************************
Pandas(Index=76, habilidades=[''], horas_disponiveis=6, tipo_user=0, user_id=76, adtech=0, agritech=0, biotech=0, edtech=0, fashiontech=0, fintech=1, healthtech=0)
**************************************************
Pandas(Index=79, habilidades=[''], horas_disponiveis=4, tipo_user=1, user_id=79, adtech=0, agritech=0, biotech=0, edtech=1, fashiontech=0, fintech=0, healthtech=0)
**************************************************
Pandas(Index=82, habilidades=[''], horas_disponiveis=8, tipo_user=1, user_id=82, adtech=0, agritech=1, biotech=0, edtech=0, fashiontech=0, fintech=0, healthtech=0)
**************************************************
Pandas(Index=87, habilidades=[''], horas_disponiveis=6, tipo_user=1, user_id=87, adtech=1, agritech=0, biotech=0, edtech=0, fashiontech=0, fintech=0, healthtech=0)
**************************************************
Pandas(Index=90, habilidades=[''], horas_disponiveis=6, tipo_user=0, user_id=90, adtech=0, agritech=0, biotech=0, edtech=0, fashiontech=1, fintech=0, healthtech=0)
**************************************************
Pandas(Index=107, habilidades=[''], horas_disponiveis=4, tipo_user=0, user_id=107, adtech=0, agritech=0, biotech=1, edtech=0, fashiontech=0, fintech=0, healthtech=0)
**************************************************
Pandas(Index=114, habilidades=[''], horas_disponiveis=4, tipo_user=1, user_id=114, adtech=0, agritech=0, biotech=0, edtech=0, fashiontech=1, fintech=0, healthtech=0)
**************************************************
Pandas(Index=115, habilidades=[''], horas_disponiveis=6, tipo_user=1, user_id=115, adtech=0, agritech=0, biotech=1, edtech=0, fashiontech=0, fintech=0, healthtech=0)
**************************************************
Pandas(Index=122, habilidades=[''], horas_disponiveis=4, tipo_user=1, user_id=122, adtech=0, agritech=0, biotech=0, edtech=0, fashiontech=0, fintech=0, healthtech=1)
**************************************************

In [8]:
df_categ

,habilidades,horas_disponiveis,tipo_user,user_id,adtech,agritech,biotech,edtech,fashiontech,fintech,healthtech
0,"[python, php, js, scrum]",6,0,0,0,0,0,0,0,1,0
1,"[python, js, illustrator]",8,1,1,0,0,0,1,0,0,0
2,"[laravel, php, js, html]",4,0,2,0,0,1,0,0,0,0
3,"[scrum, laravel, angular, html]",6,0,3,1,0,0,0,0,0,0
4,"[js, html, css]",8,0,4,1,0,0,0,0,0,0
5,"[js, angular, ionic, html, css]",4,0,5,0,0,0,0,0,1,0
6,"[php, laravel, scrum, js, html]",4,0,6,0,0,0,0,0,1,0
7,"[js, angular, ionic, html, css]",5,1,7,0,0,0,1,0,0,0
8,"[js, html, css, illustrator]",5,0,8,0,0,0,1,0,0,0
9,"[scrum, laravel, angular, html]",8,0,9,0,0,0,0,0,0,1
10,"[ionic, js, html, css, scss]",6,1,10,0,0,0,0,0,0,1
11,"[js, angular, ionic, html]",6,1,11,0,0,0,1,0,0,0
12,"[big-data, machine-learning, python]",4,1,12,0,0,0,0,0,1,0
13,"[scikit-learn, python, html, js]",8,1,13,0,0,0,0,0,1,0
14,"[laravel, php, js, css, html]",6,1,14,0,0,0,0,0,1,0
15,"[machine-learning, ionic, js, php]",6,1,15,1,0,0,0,0,0,0
16,"[ionic, js, html, css, scss, angular]",6,1,16,1,0,0,0,0,0,0
17,"[angular, js, html, css, illustrator]",6,1,17,0,0,0,1,0,0,0
18,"[python, php, js, html, css]",4,1,18,0,0,0,1,0,0,0
19,"[js, html, css, ionic, photoshop]",4,1,19,0,0,0,1,0,0,0
20,"[big-data, machine-learning, python]",4,0,20,0,0,1,0,0,0,0
21,"[big-data, machine-learning, python]",4,0,21,0,0,1,0,0,0,0
22,"[scikit-learn, python, html, js]",8,0,22,0,0,0,0,0,0,1
23,"[angular, js, html, css]",4,0,23,1,0,0,0,0,0,0
24,"[ionic, js, html, css, scss]",6,0,24,0,0,1,0,0,0,0
25,"[scikit-learn, python, html, js]",8,0,25,0,0,0,0,0,0,1
26,"[python, php, js, html, css, scikit-learn]",4,1,26,0,0,0,0,0,0,1
27,"[big-data, machine-learning, scikit-learn]",8,1,27,0,0,0,0,0,0,1
28,"[html, php, python, css]",4,1,28,0,0,1,0,0,0,0
29,"[ionic, angular, js, html, css]",4,0,29,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
104,"[ionic, html]",5,0,104,0,0,0,1,0,0,0
105,"[machine-learning, js, scss, photoshop, laravel]",5,0,105,0,0,1,0,0,0,0
106,"[css, branding, scss]",4,1,106,1,0,0,0,0,0,0
108,"[js, scrum]",8,0,108,0,0,0,0,0,0,1
109,"[scikit-learn, seo]",8,1,109,0,0,0,0,0,0,1
110,"[branding, machine-learning]",4,1,110,0,0,0,0,0,1,0
111,"[react, html, css, js, machine-learning]",5,1,111,0,0,0,0,0,1,0
112,[react],6,1,112,0,0,0,0,0,1,0
113,"[scikit-learn, scrum]",5,0,113,0,0,0,1,0,0,0
116,"[photoshop, marketing-digital, scikit-learn, i...",5,1,116,0,0,0,0,0,1,0
117,"[illustrator, html, laravel, angular, scss]",8,0,117,0,0,0,1,0,0,0
118,"[angular, scss, branding, cakephp]",5,1,118,1,0,0,0,0,0,0
119,"[php, css, angular, html]",4,1,119,0,0,0,0,1,0,0
120,"[laravel, big-data]",6,0,120,0,0,1,0,0,0,0
121,"[html, marketing-digital]",6,1,121,0,0,0,0,0,0,1
123,"[cakephp, scikit-learn, ionic]",5,1,123,1,0,0,0,0,0,0
124,"[python, react, gestao-projetos, laravel]",5,1,124,0,0,0,0,0,1,0
125,"[photoshop, js, seo, big-data]",5,0,125,0,0,0,1,0,0,0
126,"[css, php, angular, machine-learning, branding]",6,0,126,0,0,1,0,0,0,0
127,"[js, scss]",6,0,127,0,0,0,0,1,0,0
128,"[scrum, ionic]",8,1,128,0,0,0,0,1,0,0
129,[css],4,0,129,0,0,0,0,0,0,1
130,"[scrum, photoshop, angular]",5,1,130,0,0,0,0,1,0,0
131,[ionic],4,1,131,0,0,0,0,0,0,1
132,[css],8,0,132,0,0,0,0,0,1,0
133,"[marketing-digital, css, machine-learning]",5,1,133,0,0,0,0,1,0,0
134,"[branding, php, cakephp, seo, ionic]",6,1,134,0,0,0,0,0,0,1
135,"[js, big-data, angular]",4,1,135,0,0,0,0,0,1,0
136,"[machine-learning, php, cakephp]",8,0,136,1,0,0,0,0,0,0
137,"[seo, angular, marketing-digital, ionic]",4,1,137,0,0,0,0,0,0,1

In [9]:
# Arrumando os indexes do df após deletar linhas com habilidades em branco
# Fizemos isso por causa do .join, que estava dando problema de index e gerando NaN
df_categ = df_categ.reset_index(drop=True)

mlb = preprocessing.MultiLabelBinarizer()
habilidades_col = mlb.fit_transform(df_categ['habilidades'])
 
habilidades_df = pd.DataFrame(habilidades_col,columns=mlb.classes_)
df_categ = df_categ.join(habilidades_df)

df_categ.tail()

,habilidades,horas_disponiveis,tipo_user,user_id,adtech,agritech,biotech,edtech,fashiontech,fintech,...,machine-learning,marketing-digital,photoshop,php,python,react,scikit-learn,scrum,scss,seo
114,"[marketing-digital, css, machine-learning]",5,1,133,0,0,0,0,1,0,...,1,1,0,0,0,0,0,0,0,0
115,"[branding, php, cakephp, seo, ionic]",6,1,134,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
116,"[js, big-data, angular]",4,1,135,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
117,"[machine-learning, php, cakephp]",8,0,136,1,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
118,"[seo, angular, marketing-digital, ionic]",4,1,137,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1

In [10]:
# Deletamos a coluna categorica de habilidades
df_categ.drop('habilidades',axis=1,inplace=True)

In [11]:
df_categ.tail()

,horas_disponiveis,tipo_user,user_id,adtech,agritech,biotech,edtech,fashiontech,fintech,healthtech,...,machine-learning,marketing-digital,photoshop,php,python,react,scikit-learn,scrum,scss,seo
114,5,1,133,0,0,0,0,1,0,0,...,1,1,0,0,0,0,0,0,0,0
115,6,1,134,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,1
116,4,1,135,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
117,8,0,136,1,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
118,4,1,137,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,1

In [12]:
# Export preprocessed data
csv = df_categ.to_csv(path_or_buf='./data_json_preprocessed.csv',encoding='utf-8')